const std = @import("std");

pub const Counters = struct {
    anon: ?u64,
    file: ?u64,
    kernel: ?u64,
    kernel_stack: ?u64,
    pagetables: ?u64,
    sec_pagetables: ?u64,
    percpu: ?u64,
    sock: ?u64,
    vmalloc: ?u64,
    shmem: ?u64,
    zswap: ?u64,
    zswapped: ?u64,
    file_mapped: ?u64,
    file_dirty: ?u64,
    file_writeback: ?u64,
    swapcached: ?u64,
    anon_thp: ?u64,
    file_thp: ?u64,
    shmem_thp: ?u64,
    inactive_anon: ?u64,
    active_anon: ?u64,
    inactive_file: ?u64,
    active_file: ?u64,
    unevictable: ?u64,
    slab_reclaimable: ?u64,
    slab_unreclaimable: ?u64,
    slab: ?u64,
    hugetlb: ?u64,
    workingset_refault_anon: ?u64,
    workingset_refault_file: ?u64,
    workingset_activate_anon: ?u64,
    workingset_activate_file: ?u64,
    workingset_restore_anon: ?u64,
    workingset_restore_file: ?u64,
    workingset_nodereclaim: ?u64,
    pgdemote_kswapd: ?u64,
    pgdemote_direct: ?u64,
    pgdemote_khugepaged: ?u64,
    pgdemote_proactive: ?u64,
    pgpromote_success: ?u64,
    pgscan: ?u64,
    pgsteal: ?u64,
    pswpin: ?u64,
    pswpout: ?u64,
    pgscan_kswapd: ?u64,
    pgscan_direct: ?u64,
    pgscan_khugepaged: ?u64,
    pgscan_proactive: ?u64,
    pgsteal_kswapd: ?u64,
    pgsteal_direct: ?u64,
    pgsteal_khugepaged: ?u64,
    pgsteal_proactive: ?u64,
    pgfault: ?u64,
    pgmajfault: ?u64,
    pgrefill: ?u64,
    pgactivate: ?u64,
    pgdeactivate: ?u64,
    pglazyfree: ?u64,
    pglazyfreed: ?u64,
    swpin_zero: ?u64,
    swpout_zero: ?u64,
    zswpin: ?u64,
    zswpout: ?u64,
    zswpwb: ?u64,
    thp_fault_alloc: ?u64,
    thp_collapse_alloc: ?u64,
    thp_swpout: ?u64,
    thp_swpout_fallback: ?u64,
    numa_pages_migrated: ?u64,
    numa_pte_updates: ?u64,
    numa_hint_faults: ?u64,
};

pub fn fromMap(map: *const std.StringHashMap(u64)) Counters {
    return .{
        .anon = map.get("anon"),
        .file = map.get("file"),
        .kernel = map.get("kernel"),
        .kernel_stack = map.get("kernel_stack"),
        .pagetables = map.get("pagetables"),
        .sec_pagetables = map.get("sec_pagetables"),
        .percpu = map.get("percpu"),
        .sock = map.get("sock"),
        .vmalloc = map.get("vmalloc"),
        .shmem = map.get("shmem"),
        .zswap = map.get("zswap"),
        .zswapped = map.get("zswapped"),
        .file_mapped = map.get("file_mapped"),
        .file_dirty = map.get("file_dirty"),
        .file_writeback = map.get("file_writeback"),
        .swapcached = map.get("swapcached"),
        .anon_thp = map.get("anon_thp"),
        .file_thp = map.get("file_thp"),
        .shmem_thp = map.get("shmem_thp"),
        .inactive_anon = map.get("inactive_anon"),
        .active_anon = map.get("active_anon"),
        .inactive_file = map.get("inactive_file"),
        .active_file = map.get("active_file"),
        .unevictable = map.get("unevictable"),
        .slab_reclaimable = map.get("slab_reclaimable"),
        .slab_unreclaimable = map.get("slab_unreclaimable"),
        .slab = map.get("slab"),
        .hugetlb = map.get("hugetlb"),
        .workingset_refault_anon = map.get("workingset_refault_anon"),
        .workingset_refault_file = map.get("workingset_refault_file"),
        .workingset_activate_anon = map.get("workingset_activate_anon"),
        .workingset_activate_file = map.get("workingset_activate_file"),
        .workingset_restore_anon = map.get("workingset_restore_anon"),
        .workingset_restore_file = map.get("workingset_restore_file"),
        .workingset_nodereclaim = map.get("workingset_nodereclaim"),
        .pgdemote_kswapd = map.get("pgdemote_kswapd"),
        .pgdemote_direct = map.get("pgdemote_direct"),
        .pgdemote_khugepaged = map.get("pgdemote_khugepaged"),
        .pgdemote_proactive = map.get("pgdemote_proactive"),
        .pgpromote_success = map.get("pgpromote_success"),
        .pgscan = map.get("pgscan"),
        .pgsteal = map.get("pgsteal"),
        .pswpin = map.get("pswpin"),
        .pswpout = map.get("pswpout"),
        .pgscan_kswapd = map.get("pgscan_kswapd"),
        .pgscan_direct = map.get("pgscan_direct"),
        .pgscan_khugepaged = map.get("pgscan_khugepaged"),
        .pgscan_proactive = map.get("pgscan_proactive"),
        .pgsteal_kswapd = map.get("pgsteal_kswapd"),
        .pgsteal_direct = map.get("pgsteal_direct"),
        .pgsteal_khugepaged = map.get("pgsteal_khugepaged"),
        .pgsteal_proactive = map.get("pgsteal_proactive"),
        .pgfault = map.get("pgfault"),
        .pgmajfault = map.get("pgmajfault"),
        .pgrefill = map.get("pgrefill"),
        .pgactivate = map.get("pgactivate"),
        .pgdeactivate = map.get("pgdeactivate"),
        .pglazyfree = map.get("pglazyfree"),
        .pglazyfreed = map.get("pglazyfreed"),
        .swpin_zero = map.get("swpin_zero"),
        .swpout_zero = map.get("swpout_zero"),
        .zswpin = map.get("zswpin"),
        .zswpout = map.get("zswpout"),
        .zswpwb = map.get("zswpwb"),
        .thp_fault_alloc = map.get("thp_fault_alloc"),
        .thp_collapse_alloc = map.get("thp_collapse_alloc"),
        .thp_swpout = map.get("thp_swpout"),
        .thp_swpout_fallback = map.get("thp_swpout_fallback"),
        .numa_pages_migrated = map.get("numa_pages_migrated"),
        .numa_pte_updates = map.get("numa_pte_updates"),
        .numa_hint_faults = map.get("numa_hint_faults"),
    };
}
